### ISSUE TITLE
Uncaught abort() at Error

### ISSUE THREAD

**Issue by kaushik-evani** [higuma/web-audio-recorder-js#12]
This was working alright on chrome initially. Then I tested on Firefox and I started getting this error. I experimented here and there in the code, and then suddenly this error stated coming on chrome as well.

`Uncaught abort() at Error
    at jsStackTrace (http://localhost:9000/lib/OggVorbisEncoder.min.js:1:20761)
    at stackTrace (http://localhost:9000/lib/OggVorbisEncoder.min.js:1:20944)
    at Object.abort (http://localhost:9000/lib/OggVorbisEncoder.min.js:13:29426)
    at _abort (http://localhost:9000/lib/OggVorbisEncoder.min.js:1:31504)
    at Md (http://localhost:9000/lib/OggVorbisEncoder.min.js:6:60155)
    at Eb (http://localhost:9000/lib/OggVorbisEncoder.min.js:5:16630)
    at Fb (http://localhost:9000/lib/OggVorbisEncoder.min.js:5:17644)
    at Ad (http://localhost:9000/lib/OggVorbisEncoder.min.js:6:39926)
    at Encoder.process (http://localhost:9000/lib/OggVorbisEncoder.min.js:13:30916)
    at Encoder.finish (http://localhost:9000/lib/OggVorbisEncoder.min.js:13:30632)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.`

All the library files are in lib/ folder. I have  also checked network logs in the page to see if I am successfully able to get all the necessary files. All are fetched.
I couldn't understand this error after some research as well. Help would be greatly appreciated. Thank you!

**Comment by clecap** [comment]
I also can produce this problem.

However, I found a workaround: For me, this shows up only when I set encodeAfterRecord to false.
